### api calls for our DEMOAPI

GET http://localhost:3000/ HTTP/1,1



### GET all blogpost

GET http://localhost:3000/api/blogposts HTTP/1,1

### GET one blogposts

GET http://localhost:3000/api/blogposts/2 HTTP/1,1

### GET all users

GET http://localhost:3000/api/users/ 

### GET user by ID

GET http://localhost:3000/api/users/7

### GET all todos

GET http://localhost:3000/api/todos/ 

### GET todos by ID

GET http://localhost:3000/api/todos/101

### Post Blog
POST http://localhost:3000/api/blogposts/ HTTP/1.1
content-type: application/json

{
    "title": "Sample blog post title",
    "body": "Text of a sample blog post",
    "userId": 2
}

### Put test Blog
PUT http://localhost:3000/api/blogposts/1 HTTP/1.1
content-type: application/json

{
   "id": 1,
   "title": "Our trip to Paris, France",
   "body": "We finally saw Eiffel Tower.",
   "userId": 2
}

###DELETE Blog
DELETE http://localhost:3000/api/blogposts/1 HTTP/1.1

### Post todos
POST http://localhost:3000/api/todos/ HTTP/1.1
content-type: application/json

{
    "title": "need to do this",
    "userId": 2
}

### Put test todos
PUT http://localhost:3000/api/todos/1 HTTP/1.1
content-type: application/json

{
   "id": 1,
   "title": "Go to France",
   "completed":false,
   "userId": 2
}

###DELETE todos
DELETE http://localhost:3000/api/todos/1 HTTP/1.1

### Post User
Post http://localhost:3000/api/users/  HTTP/1.1
content-type: application/json

{
"id": 1001,
"name": "John",
"username": "Bret",
"email": "Sincere@april.biz",
"address": {
    "street": "Kulas Light",
    "suite": "Apt. 556",
    "city": "Gwenborough",
    "zipcode": "92998-3874",
    "geo": {
    "lat": "-37.3159",
    "lng": "81.1496"
}
},
"phone": "1-770-736-8031 x56442",
"website": "hildegard.org",
"company": {
"name": "Romaguera-Crona",
"catchPhrase": "Multi-layered client-server neural-net",
"bs": "harness real-time e-markets"
}
}

### Put User
Put http://localhost:3000/api/users/1  HTTP/1.1
content-type: application/json

{
"id": 1,
"name": "John",
"username": "Bret",
"email": "Sincere@april.biz",
"address": {
    "street": "Kulas Light",
    "suite": "Apt. 556",
    "city": "Gwenborough",
    "zipcode": "92998-3874",
    "geo": {
    "lat": "-37.3159",
    "lng": "81.1496"
}
},
"phone": "1-770-736-8031 x56442",
"website": "hildegard.org",
"company": {
"name": "Romaguera-Crona",
"catchPhrase": "Multi-layered client-server neural-net",
"bs": "harness real-time e-markets"
}
}

###DELETE todos
DELETE http://localhost:3000/api/users/1 HTTP/1.1